### ISSUE TITLE
Inconsistent use of we vs us

### ISSUE THREAD

**Issue by tgvashworth** [CodeYourFuture/immersive-go-course#14]
The project readmes make inconsistent use of "we" and "you":

* "In this project you're going to..."
* "In your command line/terminal, make sure your..."
* "We've been using single-quotes..."
* "In this exercise, we chose to make some of our requests fail fast..."

We should make this consistent: always use "we". 

We should also always use active voice ("We are going to build a server..." vs "A server will be built...") 

This issue applies to existing `README.md` files on `main`: fixing `impl` branched is out of scope.

One exception will be if the trainee has to figure it out for themselves. In this case it is OK: "This will be up to you to figure out!"

**Comment by bandya2003** [comment]
I would like to edit the readme file for editing the inconsistency. Can you please assign this issue to me , I would try my best to resolve it .

**Comment by tgvashworth** [comment]
Hey! Sure. I think it would be good to break this up into several PRs that fix each `README.md` in turn. Maybe `cli-files/README.md` first?

**Comment by bandya2003** [comment]
Sure , I would start working on it 
Thanks a lot again for assigning the issue to me

**Comment by illicitonion** [comment]
Thanks so much for the help here, @bandya2003!

**Comment by bandya2003** [comment]
Thanks a lot for giving me the opportunity for contributing to your project !!! @illicitonion @tgvashworth
