### ISSUE TITLE
Typo in the Sentence 

### ISSUE THREAD

**Issue by reversearrow** [CodeYourFuture/immersive-go-course#140]
## Description

I found a typo in the statement in the document #2 of the [distributed-software-systems-architecture](https://github.com/CodeYourFuture/immersive-go-course/tree/main/primers/distributed-software-systems-architecture)

https://github.com/CodeYourFuture/immersive-go-course/blob/main/primers/distributed-software-systems-architecture/state.md#cache-invalidation-cache-invalidation

## Expected Behavior 

There are three hard things in computer science: cache invalidation, naming things, and off-by-one errors.

The statement should say three instead of two. 

## Actual Behavior 

There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.

The statement says two instead of three.

**Comment by SallyMcGrath** [comment]
:) Thank you!

But it's a joke! It's an off by one error.  😉
